### ISSUE TITLE
adio2 module not found error while importing ldrb

### ISSUE THREAD

**Issue by AnoopRKulkarni** [finsberg/fenicsx-ldrb#18]
I have installed the fenicsx on my Ubuntu 22.04 as follows:

```
sudo add-apt-repository ppa:fenics-packages/fenics
sudo apt update
sudo apt install fenicsx
conda install -c conda-forge fenics-dolfinx mpich pyvista
```
When I import fenicx-ldrb though, I get adios2 module not found error as below..

```
(base) $ python
Python 3.12.4 | packaged by conda-forge | (main, Jun 17 2024, 10:23:07) [GCC 12.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import dolfinx
>>> import ldrb
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/anoop/miniconda3/lib/python3.12/site-packages/ldrb/__init__.py", line 3, in <module>
    from . import calculus, io, ldrb, utils
  File "/home/anoop/miniconda3/lib/python3.12/site-packages/ldrb/io.py", line 8, in <module>
    import adios4dolfinx
  File "/home/anoop/miniconda3/lib/python3.12/site-packages/adios4dolfinx/__init__.py", line 11, in <module>
    from .checkpointing import (
  File "/home/anoop/miniconda3/lib/python3.12/site-packages/adios4dolfinx/checkpointing.py", line 14, in <module>
    import adios2
ModuleNotFoundError: No module named 'adios2'
>>> 
```

Thanks in advance for any leads..
~anoop

**Comment by AnoopRKulkarni** [comment]
**UPDATE**

BTW, I already have a local installation of PETSc. Could the mpi of that be conflicting with the one installed by `fenicsx`? How do I have both PETSc and FEniCSx co-existing?

**Comment by AnoopRKulkarni** [comment]
**UPDATE 2**

It did look like my local installation of PETSc was causing the errors. So I decided to build `fenicsx` from sources. Looks like it went well

```
$ pip list|grep fenics
fenics-basix      0.9.0.dev0
fenics-dolfinx    0.9.0.dev0
fenics-ffcx       0.9.0.dev0
fenics-ufl        2024.2.0.dev0
fenicsx-ldrb      0.1.6
$ 
```

Now, when I try to import `fenicsx-ldrb`, I get the following error:

```
$ python
Python 3.10.2 (main, Aug 12 2023, 21:20:16) [GCC 11.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import dolfinx
>>> import ldrb
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/anoop/.pyenv/versions/3.10.2/lib/python3.10/site-packages/ldrb/__init__.py", line 3, in <module>
    from . import calculus, io, ldrb, utils
  File "/home/anoop/.pyenv/versions/3.10.2/lib/python3.10/site-packages/ldrb/ldrb.py", line 10, in <module>
    from dolfinx.fem.petsc import LinearProblem
  File "/home/anoop/.pyenv/versions/3.10.2/lib/python3.10/site-packages/dolfinx/fem/petsc.py", line 29, in <module>
    from dolfinx.cpp.fem.petsc import discrete_gradient as _discrete_gradient
ModuleNotFoundError: No module named 'dolfinx.cpp.fem.petsc'; 'dolfinx.cpp.fem' is not a package
>>> 
```

Does this sound familiar to you? 

Thanks
~anoop

**Comment by AnoopRKulkarni** [comment]
**UPDATE**

I suspected some faulty python interface installation of dolfinx, so decided to rebuild from scratch. After I install `fenicsx-ldrb`, I still need to do `pip install adios2` but there are no errors now.

I am getting an error while import `adios4dolfinx` saying
`AttributeError: module 'dolfinx.fem' has no attribute 'FunctionSpaceBase'. Did you mean: 'FunctionSpace'?`

Is there a base version of `fenicsx` that ldrb has been tested against? Maybe I can revert back to those versions? I am currently using 0.9 of fenicsx from the FEniCS repository.

Thanks
~anoop

**Comment by AnoopRKulkarni** [comment]
This is resolved.

As I had a local PETSc installation with an mpicc, I ended up building fenicsx from sources. Then needed to build adios2 with mpicc, upgrade adios4dolfinx and now fenicsx and ldrb are both running as expected.
